spring:
  cloud:
    gateway:
      routes:
        - id: student-service
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/student/**
          filters:
            - RedirectToAuthenticationFilter

        - id: course-service
          uri: lb://COURSE-SERVICE
          predicates:
            - Path=/course/**
          filters:
            - RedirectToAuthenticationFilter

        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/auth/**

  application:
    name: GATEWAY-SERVICE

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/